/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.jetbrains:annotations:24.1.0")
    compileOnly("org.spigotmc:spigot-api:1.20.6-R0.1-SNAPSHOT")
    compileOnly("org.spigotmc:spigot:1.21-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.11.6")
}

group = "me.calrl"
version = "2.3.0"
description = "Hubbly"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.processResources {
    filesMatching("**/plugin.yml") {
        // Use a map to define the variables for substitution
        expand("project" to project, "version" to project.version)
    }
}

// Define a custom task to copy the JAR file
// Define a custom task to copy the JAR file
//tasks.register<Copy>("copyJar") {
//    val jarTask = tasks.named("jar") // Get reference to the jar task
//    from(jarTask.get().outputs.files)  // Source directory (where the JAR file is located)
//    into("C:\\Users\\Callum\\Desktop\\server 1.21\\plugins")  // Destination directory
//    include("*.jar")  // Include only JAR files
//}
//
//// Make sure the custom task runs after the JAR is created
//tasks.named("build") {
//    finalizedBy("copyJar")
//}
