name: Manual Build - Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache local Maven repo (for Spigot)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-spigot-1.20.6
          restore-keys: |
            m2-${{ runner.os }}-spigot-

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Compile Spigot 1.20.6 with BuildTools
        uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.20.6

      - name: Extract version from build.gradle.kts
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=version = ")[^"]+' build.gradle.kts)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Gradle clean
        run: ./gradlew clean

      - name: Run tests
        run: ./gradlew test

      - name: Build plugin
        run: ./gradlew build

      - name: Create GitHub Release and Upload JAR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate tar.gz and zip archives for current commit
          git archive --format=tar.gz --output=source-${VERSION}.tar.gz HEAD
          git archive --format=zip    --output=source-${VERSION}.zip    HEAD
          
          # Create the GitHub release and upload all assets
          gh release create "v${VERSION}" \
            "build/libs/Hubbly-${VERSION}.jar#Hubbly-${VERSION}.jar" \
            "source-${VERSION}.zip#Source Code (ZIP)" \
            "source-${VERSION}.tar.gz#Source Code (TAR.GZ)" \
            --title "Hubbly ${VERSION}" \
            --notes-file <(awk "/^## \\[${VERSION//./\\.}\\]/ {print; found=1; next} /^## \\[/ && found {exit} found" CHANGELOG.md | sed '1d') \
            --draft